[package]
name = "ferry"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.39", features = ["derive"]}
crossterm = "0.29.0"
directories = "6.0.0"
ratatui = "0.29.0"
regex = "1.11.1"
walkdir = "2.5.0"
